### ISSUE TITLE
Investigate why creating PRs doesnt fail the workflow

### ISSUE THREAD

**Issue by egilsster** [qlik-oss/qmfe-actions#132]
https://github.com/qlik-oss/qmfe-actions/blob/v1/update-qmfe-import-map/src/index.ts#L47

This should fail the workflow, or at least that is what we want.

**Comment by LiKang6688** [comment]
why do we separate qmfe-workflows and qmfe-actions and one in qlik-trial and another one in qlik-oss?

**Comment by egilsster** [comment]
> why do we separate qmfe-workflows and qmfe-actions and one in qlik-trial and another one in qlik-oss?

When we started this project it wasn't possible to re-use private actions. Now that we can, we could potentially just consolidate these into to our internal repo.
